name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_APP_DIR }}

            # If repo doesn’t exist, clone it; else pull latest
            if [ ! -d ".git" ]; then
              git clone https://github.com/KaviyaKanakaraj/api-sample.git .
            else
              git reset --hard
              git pull origin ${{ secrets.DEPLOY_BRANCH }}
            fi

            # --- BACKEND ---
            cd backend
            npm install
            if pm2 list | grep -q "backend"; then
              pm2 restart backend
            else
              pm2 start server.js --name backend
            fi
            cd ..

            # --- FRONTEND ---
            cd frontend
            if pm2 list | grep -q "frontend"; then
              pm2 restart frontend
            else
              pm2 start "http-server -p 8080 -a 0.0.0.0 -c-1 ." --name frontend
            fi
            cd ..

            pm2 save
